AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rake