AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

inherit_from: .rubocop_todo.yml
